name: Run Python
on:
  workflow_dispatch:
  push:
  schedule:
    - cron:  "* 9/9 * * *"
jobs:
  my_job:
    name: test-python
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: 1. Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
                    
      #- name: 2. Install dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install requests
      #    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: 3. Run Python Script
        run: |
          python hello.py

      #- name: 4. Show Result
      #  run: |
      #    echo "OK!"
          
      - name: 5. commit and push 
        run: |
          git diff
          git config --global user.email "syjsu@qq.com" && git config --global user.name "syjsu"
          git pull
          git add -A
          git commit -m "Update files" || exit 0
          git push
